# Generated by Django 3.1.5 on 2021-02-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='replyemail',
            field=models.BooleanField(default=False),
        ),
    ]
